"""
VAE Output Post-Processing
Fixes invalid values generated by the VAE to ensure all outputs are valid.

Usage:
    from vae_postprocessor import fix_vae_output
    
    raw_output = vae.generate()  # Generates invalid values
    fixed_output = fix_vae_output(raw_output)  # Fixes them!
"""

import numpy as np
import pandas as pd
from variable_constraints import (
    ALL_VARIABLES, 
    SUBSISTENCE_VARS, 
    CONSTRAINTS,
    get_variable_type,
    get_valid_range
)


def fix_categorical_variable(var_name, raw_value):
    """
    Fix a categorical variable by rounding to nearest valid value.
    
    Example:
        EA033 = 1.38 → rounds to nearest valid value (1)
        EA033 = 7.2  → clips to max valid value (5)
    """
    valid_values = get_valid_range(var_name)
    
    if valid_values is None:
        return raw_value
    
    # Find nearest valid value
    nearest = min(valid_values, key=lambda x: abs(x - raw_value))
    return nearest


def fix_integer_variable(var_name, raw_value):
    """
    Fix an integer variable by rounding and clipping to valid range.
    
    Example:
        EA001 = 5.7 → rounds to 6
        EA001 = 15  → clips to 9 (max)
        EA001 = -2  → clips to 0 (min)
    """
    min_val, max_val = get_valid_range(var_name)
    
    # Round to integer
    rounded = int(round(raw_value))
    
    # Clip to valid range
    clipped = np.clip(rounded, min_val, max_val)
    
    return int(clipped)


def fix_continuous_variable(var_name, raw_value):
    """
    Fix a continuous variable by clipping to valid range.
    
    Example:
        Temp = 118.4 → clips to 40.0 (max)
        Temp = -50.0 → clips to -20.0 (min)
    """
    min_val, max_val = get_valid_range(var_name)
    
    # Clip to valid range
    clipped = np.clip(raw_value, min_val, max_val)
    
    return clipped


def fix_subsistence_sum(values_dict, fixed_var=None):
    """
    Ensure EA001-EA005 sum to exactly 10.
    
    Algorithm:
    1. Get current values for EA001-EA005
    2. Normalize them to sum to 10
    3. Round to integers
    4. Fix any rounding errors by adjusting largest value
    
    Example:
        EA001=15, EA002=3, EA003=2, EA004=1, EA005=8  (sum=29)
        → Normalize to sum 10
        → EA001=5, EA002=1, EA003=1, EA004=0, EA005=3  (sum=10)
    """
    subsistence_vars = ['EA001', 'EA002', 'EA003', 'EA004', 'EA005']
    if fixed_var is not None and fixed_var not in subsistence_vars:
        fixed_var = None
    
    # Get current values (already fixed to 0-9 range)
    current_values = [values_dict[var] for var in subsistence_vars]
    current_sum = sum(current_values)
    
    # If already 10, we're done
    if current_sum == 10:
        return values_dict

    # If fixing a specific variable, only rebalance the others
    if fixed_var is not None:
        fixed_val = int(values_dict[fixed_var])
        remaining_vars = [v for v in subsistence_vars if v != fixed_var]
        remaining_values = [values_dict[v] for v in remaining_vars]
        remaining_sum = sum(remaining_values)
        target_remaining = 10 - fixed_val

        if target_remaining < 0:
            fixed_val = 10
            target_remaining = 0
            values_dict[fixed_var] = 10

        if remaining_sum == 0:
            # Distribute evenly
            base = target_remaining // len(remaining_vars)
            remainder = target_remaining % len(remaining_vars)
            new_vals = [base for _ in remaining_vars]
            for i in range(remainder):
                new_vals[i] += 1
        else:
            normalized = [v * target_remaining / remaining_sum for v in remaining_values]
            new_vals = [int(round(v)) for v in normalized]

        # Clip to [0, 9]
        new_vals = [int(np.clip(v, 0, 9)) for v in new_vals]

        # Fix rounding errors to hit target_remaining
        while sum(new_vals) != target_remaining:
            if sum(new_vals) < target_remaining:
                # Add to largest with room
                idxs = sorted(range(len(new_vals)), key=lambda i: new_vals[i], reverse=True)
                for idx in idxs:
                    if new_vals[idx] < 9:
                        new_vals[idx] += 1
                        break
            else:
                # Subtract from smallest > 0
                idxs = sorted(range(len(new_vals)), key=lambda i: new_vals[i])
                for idx in idxs:
                    if new_vals[idx] > 0:
                        new_vals[idx] -= 1
                        break

        for i, var in enumerate(remaining_vars):
            values_dict[var] = new_vals[i]

        return values_dict
    
    # If sum is 0, set equal distribution
    if current_sum == 0:
        values_dict['EA001'] = 2
        values_dict['EA002'] = 2
        values_dict['EA003'] = 2
        values_dict['EA004'] = 2
        values_dict['EA005'] = 2
        return values_dict
    
    # Normalize to sum to 10
    normalized = [v * 10.0 / current_sum for v in current_values]
    
    # Round to integers
    rounded = [int(round(v)) for v in normalized]
    
    # Fix rounding errors
    while sum(rounded) != 10:
        if sum(rounded) < 10:
            # Add 1 to the largest value
            max_idx = rounded.index(max(rounded))
            if rounded[max_idx] < 9:  # Don't exceed max
                rounded[max_idx] += 1
            else:
                # Find next largest that's not maxed out
                for i in sorted(range(len(rounded)), key=lambda x: rounded[x], reverse=True):
                    if rounded[i] < 9:
                        rounded[i] += 1
                        break
        else:
            # Subtract 1 from the smallest non-zero value
            non_zero = [i for i, v in enumerate(rounded) if v > 0]
            if non_zero:
                min_idx = min(non_zero, key=lambda x: rounded[x])
                rounded[min_idx] -= 1
            else:
                # Shouldn't happen, but just in case
                rounded[0] = max(0, rounded[0] - 1)
    
    # Update dictionary
    for i, var in enumerate(subsistence_vars):
        values_dict[var] = rounded[i]
    
    return values_dict


def apply_logic_rules(values_dict):
    """
    Apply coherence rules to improve anthropological plausibility.
    Rules are conservative and only applied if needed.
    """
    # Helper to cap and ensure integers for categorical/integer fields
    def cap_int(var_name, max_value):
        if var_name in values_dict:
            values_dict[var_name] = int(min(values_dict[var_name], max_value))

    def ensure_min(var_name, min_value):
        if var_name in values_dict:
            values_dict[var_name] = int(max(values_dict[var_name], min_value))

    # Rule 1: Nomadic or semi-nomadic -> low agriculture
    if 'EA030' in values_dict and 'EA005' in values_dict:
        if values_dict['EA030'] <= 2:
            if values_dict['EA005'] > 3:
                values_dict['EA005'] = 3
                fix_subsistence_sum(values_dict, fixed_var='EA005')
            # Lower agriculture intensity if present
            cap_int('EA028', 3)

    # Rule 2: High agriculture -> more settled
    if 'EA005' in values_dict and 'EA030' in values_dict:
        if values_dict['EA005'] >= 7:
            ensure_min('EA030', 5)

    # Rule 3: No hierarchy -> no complex stratification
    if 'EA033' in values_dict and 'EA066' in values_dict:
        if values_dict['EA033'] == 1 and values_dict['EA066'] > 2:
            values_dict['EA066'] = 2

    # Rule 4: Cold climates -> lower agriculture
    if 'AnnualMeanTemperature' in values_dict and 'EA005' in values_dict:
        if values_dict['AnnualMeanTemperature'] < 5:
            if values_dict['EA005'] > 4:
                values_dict['EA005'] = 4
                fix_subsistence_sum(values_dict, fixed_var='EA005')
            cap_int('EA028', 3)

    return values_dict


def fix_vae_output(raw_output, column_names=None):
    """
    Main function to fix all invalid values in VAE output.
    
    Args:
        raw_output: Can be:
            - numpy array (1D or 2D)
            - pandas Series
            - pandas DataFrame
            - dict
        column_names: List of column names (if raw_output is numpy array)
    
    Returns:
        Same type as input, but with all values fixed
    
    Example:
        # As numpy array
        raw = np.array([5.2, 8.7, 1.3, 118.4, 6.06, ...])
        fixed = fix_vae_output(raw, column_names=model.column_names)
        
        # As dict
        raw = {'EA033': 1.38, 'EA001': 15, 'Temp': 118.4}
        fixed = fix_vae_output(raw)
    """
    
    # Convert input to dict for processing
    if isinstance(raw_output, dict):
        values_dict = raw_output.copy()
    
    elif isinstance(raw_output, pd.Series):
        values_dict = raw_output.to_dict()
    
    elif isinstance(raw_output, pd.DataFrame):
        if len(raw_output) == 1:
            values_dict = raw_output.iloc[0].to_dict()
        else:
            # Process multiple rows
            return pd.DataFrame([
                fix_vae_output(raw_output.iloc[i])
                for i in range(len(raw_output))
            ])
    
    elif isinstance(raw_output, np.ndarray):
        if raw_output.ndim == 1:
            if column_names is None:
                raise ValueError("column_names required for numpy array input")
            values_dict = dict(zip(column_names, raw_output))
        elif raw_output.ndim == 2:
            # Process multiple rows
            if column_names is None:
                raise ValueError("column_names required for numpy array input")
            return np.array([
                list(fix_vae_output(raw_output[i], column_names).values())
                for i in range(len(raw_output))
            ])
        else:
            raise ValueError(f"Unsupported array dimension: {raw_output.ndim}")
    
    else:
        raise ValueError(f"Unsupported input type: {type(raw_output)}")
    
    # Fix each variable based on its type
    fixed_dict = {}
    
    for var_name, raw_value in values_dict.items():
        var_type = get_variable_type(var_name)
        
        if var_type is None:
            # Unknown variable, keep as-is
            fixed_dict[var_name] = raw_value
            continue
        
        if var_type == 'categorical':
            fixed_dict[var_name] = fix_categorical_variable(var_name, raw_value)
        
        elif var_type == 'integer':
            fixed_dict[var_name] = fix_integer_variable(var_name, raw_value)
        
        elif var_type == 'continuous':
            fixed_dict[var_name] = fix_continuous_variable(var_name, raw_value)
        
        else:
            fixed_dict[var_name] = raw_value

    # Drop EA202 from outputs (undefined/unstable)
    if 'EA202' in fixed_dict:
        del fixed_dict['EA202']
    
    # Apply inter-variable constraints
    subsistence_vars = ['EA001', 'EA002', 'EA003', 'EA004', 'EA005']
    if all(var in fixed_dict for var in subsistence_vars):
        fixed_dict = fix_subsistence_sum(fixed_dict)

    # Apply logic coherence rules
    fixed_dict = apply_logic_rules(fixed_dict)
    
    # Return in same format as input
    if isinstance(raw_output, dict):
        return fixed_dict
    elif isinstance(raw_output, pd.Series):
        return pd.Series(fixed_dict)
    elif isinstance(raw_output, np.ndarray) and raw_output.ndim == 1:
        return np.array([fixed_dict[col] for col in column_names])
    else:
        return fixed_dict


def validate_fixed_output(fixed_output):
    """
    Validate that all values in the fixed output are valid.
    Returns (is_valid, error_messages)
    
    Example:
        fixed = fix_vae_output(raw)
        is_valid, errors = validate_fixed_output(fixed)
        if not is_valid:
            print("Errors:", errors)
    """
    from variable_constraints import validate_value
    
    errors = []
    
    if isinstance(fixed_output, dict):
        values_dict = fixed_output
    elif isinstance(fixed_output, pd.Series):
        values_dict = fixed_output.to_dict()
    else:
        raise ValueError("validate_fixed_output requires dict or Series")
    
    # Check each variable
    for var_name, value in values_dict.items():
        is_valid, msg = validate_value(var_name, value)
        if not is_valid:
            errors.append(msg)
    
    # Check subsistence sum
    subsistence_vars = ['EA001', 'EA002', 'EA003', 'EA004', 'EA005']
    if all(var in values_dict for var in subsistence_vars):
        subsistence_sum = sum(values_dict[var] for var in subsistence_vars)
        if subsistence_sum != 10:
            errors.append(f"Subsistence variables sum to {subsistence_sum}, should be 10")
    
    return len(errors) == 0, errors


# ==============================================================================
# INTEGRATION WITH EXISTING VAE CODE
# ==============================================================================

def add_postprocessing_to_vae(vae_model):
    """
    Wrap a VAE model's generate method with post-processing.
    
    Usage:
        vae = load_vae_model('dream_machine_vae.pth')
        vae = add_postprocessing_to_vae(vae)
        
        # Now generates valid outputs automatically!
        society = vae.generate()
    """
    original_generate = vae_model.generate
    
    def generate_with_postprocessing(*args, **kwargs):
        raw_output = original_generate(*args, **kwargs)
        fixed_output = fix_vae_output(raw_output, column_names=vae_model.column_names)
        return fixed_output
    
    vae_model.generate = generate_with_postprocessing
    return vae_model


# ==============================================================================
# COMMAND LINE TEST
# ==============================================================================

if __name__ == '__main__':
    print("=== VAE POST-PROCESSING TEST ===\n")
    
    # Test case 1: Invalid categorical
    print("Test 1: Categorical variable (EA033)")
    print("Raw:   EA033 = 1.38")
    fixed = fix_categorical_variable('EA033', 1.38)
    print(f"Fixed: EA033 = {fixed}")
    print()
    
    # Test case 2: Invalid integer
    print("Test 2: Integer variable (EA001)")
    print("Raw:   EA001 = 15")
    fixed = fix_integer_variable('EA001', 15)
    print(f"Fixed: EA001 = {fixed}")
    print()
    
    # Test case 3: Invalid continuous
    print("Test 3: Continuous variable (Temperature)")
    print("Raw:   Temp = 118.4")
    fixed = fix_continuous_variable('AnnualMeanTemperature', 118.4)
    print(f"Fixed: Temp = {fixed}")
    print()
    
    # Test case 4: Full society with multiple errors
    print("Test 4: Complete invalid society")
    raw_society = {
        'EA001': 15,  # Invalid (>9)
        'EA002': 3,
        'EA003': 2,
        'EA004': 1,
        'EA005': 8,
        'EA033': 1.38,  # Invalid (not integer)
        'EA043': 6.06,  # Invalid (out of range)
        'AnnualMeanTemperature': 118.4,  # Invalid (too high)
        'MonthlyMeanPrecipitation': 84419.52,  # Invalid (way too high)
        'TemperatureConstancy': 50.0,
        'EA009': 2,
        'EA012': 6,
        'EA042': 7,
        'EA070': 1,
        'EA028': 5,
        'EA030': 7,
        'EA066': 3,
        'EA039': 1
    }
    
    print("Raw society:")
    for k, v in sorted(raw_society.items()):
        print(f"  {k}: {v}")
    
    fixed_society = fix_vae_output(raw_society)
    
    print("\nFixed society:")
    for k, v in sorted(fixed_society.items()):
        print(f"  {k}: {v}")
    
    # Validate the fixed output
    is_valid, errors = validate_fixed_output(fixed_society)
    
    print(f"\nValidation: {'✓ VALID' if is_valid else '✗ INVALID'}")
    if errors:
        print("Errors:")
        for error in errors:
            print(f"  - {error}")
    
    # Check subsistence sum
    subsistence_sum = sum(fixed_society[var] for var in ['EA001', 'EA002', 'EA003', 'EA004', 'EA005'])
    print(f"\nSubsistence sum: {subsistence_sum} (should be 10)")
